{
 "title": "Storm Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Nice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nice avg 30 sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "substr(movingAverage(lachesis.*.schedule.thread.external.*, 30), 5,6)"
    }
   ]
  },
  {
   "title": "Nice avg 5 sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "substr(movingAverage(lachesis.*.schedule.thread.external.*, 5), 5,6)"
    }
   ]
  },
  {
   "title": "Nice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "substr(lachesis.*.schedule.thread.external.*, 5,6)"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Kafka Rate",
   "type": "timeseries",
   "description": "Kafka time series rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(kafka.experiment.external-rate.value, \"actual rate\")"
    },
    {
     "target": "alias(movingAverage(kafka.*.external-rate.value, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(kafka.*.external-rate.value, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  {
   "title": "Kafka queue",
   "type": "timeseries",
   "description": "Kafka queue size",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "Storm.*.*.*.*.*.kafka-queue-size.*"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Source Throughput",
   "type": "timeseries",
   "description": "Source throughput ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "Storm.*.*.*.source.*.emit-count.default.value"
    },
    {
     "target": "alias(movingAverage(Storm.*.*.*.source.*.emit-count.default.value, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(Storm.*.*.*.source.*.emit-count.default.value, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  {
   "title": "Sink Throughput",
   "type": "timeseries",
   "description": "Sink throughput",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "target": "Storm.*.*.*.sink.*.execute-count.*.value"
    }
   ]
  },
  {
   "title": "Source Throughput Avg",
   "type": "gauge",
   "description": "Source throughput average",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "Storm.*.*.*.source.*.emit-count.default.value | aggregateLine('avg') | aliasByNode(4,6)"
    }
   ]
  },
  {
   "title": "Sink Throughput avg",
   "type": "gauge",
   "description": "Sink throughput average",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "Storm.*.*.*.sink.*.execute-count.*.value | aggregateLine('avg') | aliasByNode(4,7)"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "target": "Storm.*.*.*.*.*.total-latency.*"
    },
    {
     "target": "alias(movingAverage(Storm.*.*.*.*.*.total-latency.*, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(Storm.*.*.*.*.*.total-latency.*, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  {
   "title": "End-to-end Latency",
   "type": "timeseries",
   "description": "End-to-end latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "target": "Storm.*.*.*.*.*.total-latency-ext.*"
    },
    {
     "target": "alias(movingAverage(Storm.*.*.*.*.*.total-latency-ext.*,5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(Storm.*.*.*.*.*.total-latency-ext.*,30), \"moving avg 30 sec\")"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Input Queue Sizes",
   "type": "timeseries",
   "description": "Input queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "target": "substr(Storm.*.*.*.*.*.receive.population.value, 4, 5)"
    }
   ]
  },
  {
   "title": "Output Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "target": "substr(Storm.*.*.*.*.*.sendqueue.population.value, 4, 5)"
    }
   ]
  },
  {
   "title": "Input Queue Sizes AVG 30 sec",
   "type": "timeseries",
   "description": "Input queue average 30 sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "target": "substr(movingAverage(Storm.*.*.*.*.*.receive.population.value, 30), 4, 5)"
    }
   ]
  },
  {
   "title": "Output Queue Sizes AVG 30 sec",
   "type": "timeseries",
   "description": "Output queue average 30 sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "target": "substr(movingAverage(Storm.*.*.*.*.*.sendqueue.population.value, 30), 4, 5)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Storm Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    { "target": "Storm.*.utilization.memory.mb" },
    {
     "target": "alias(movingAverage(Storm.*.utilization.memory.mb, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(Storm.*.utilization.memory.mb, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  {
   "title": "Lachesis Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "target": "lachesis.*.utilization.memory.mb"
    },
    {
     "target": "alias(movingAverage(lachesis.*.utilization.memory.mb, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(lachesis.*.utilization.memory.mb, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Storm CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "target": "Storm.*.utilization.cpu.percent"
    },
    {
     "target": "alias(movingAverage(Storm.*.utilization.cpu.percent, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(Storm.*.utilization.cpu.percent, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  {
   "title": "Lachesis CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "target": "lachesis.*.utilization.cpu.percent"
    },
    {
     "target": "alias(movingAverage(lachesis.*.utilization.cpu.percent, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(lachesis.*.utilization.cpu.percent, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  {
   "title": "Graphite CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "target": "graphite.*.utilization.cpu.percent"
    },
    {
     "target": "alias(movingAverage(graphite.*.utilization.cpu.percent, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(graphite.*.utilization.cpu.percent, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  { "title": "Reads and Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "Reads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "target": "Storm.*.*.*.*.*.execute-count.*.value"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "Writes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "target": "Storm.*.*.*.*.*.emit-count.*.value"
    }
   ]
  }
 ]
}