{
 "title": "Storm EdgeWise Dashboard",
 "time": { "from": "2022-04-08T09:14:25.000Z", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Nice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nice avg 30 sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "substr(movingAverage(lachesis.*.schedule.thread.external.*, 30), 5,6)"
    }
   ]
  },
  {
   "title": "Nice avg 5 sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "substr(movingAverage(lachesis.*.schedule.thread.external.*, 5), 5,6)"
    }
   ]
  },
  {
   "title": "Nice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "substr(lachesis.*.schedule.thread.external.*, 5,6)"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Source Throughput",
   "type": "timeseries",
   "description": "Source throughput ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "Storm.*.*.*.spout.*.emit-count.default.value | aliasByNode(4)"
    }
   ]
  },
  {
   "title": "Sink Throughput",
   "type": "timeseries",
   "description": "Sink throughput",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "Storm.*.*.*.*Sink.*.execute-count.*.value | aliasByNode(4,5)"
    }
   ]
  },
  {
   "title": "Source Throughput avg 30 sec",
   "type": "timeseries",
   "description": "Source throughput average 30 seconds",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "movingAverage(Storm.*.*.*.spout.*.emit-count.default.value, 30) | aliasByNode(4)"
    }
   ]
  },
  {
   "title": "Sink Throughput avg 30 secs",
   "type": "timeseries",
   "description": "Sink throughput average 30 seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "movingAverage(Storm.*.*.*.*Sink.*.execute-count.*.value, 30) | aliasByNode(4,5)"
    }
   ]
  },
  {
   "title": "Source Throughput avg",
   "type": "gauge",
   "description": "Source throughput average",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "Storm.*.*.*.spout.*.emit-count.default.value | aggregateLine('avg') | aliasByNode(4)"
    }
   ]
  },
  {
   "title": "Sink Throughput avg",
   "type": "gauge",
   "description": "Sink throughput average",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "Storm.*.*.*.*Sink.*.execute-count.*.value | aggregateLine('avg') | aliasByNode(4)"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "target": "substr(Storm.*.*.*.*.*.total-latency.*, 4, 6)"
    }
   ]
  },
  {
   "title": "Latency 5 sec",
   "type": "timeseries",
   "description": "Latency average 5 sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "target": "substr(movingAverage(Storm.*.*.*.*.*.total-latency.*, 5), 4, 6)"
    }
   ]
  },
  {
   "title": "Latency 30 sec",
   "type": "timeseries",
   "description": "Latency average 30 sec",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "target": "substr(movingAverage(Storm.*.*.*.*.*.total-latency.*, 30), 4, 6)"
    }
   ]
  },
  {
   "title": "End-to-end Latency ",
   "type": "timeseries",
   "description": "End-to-end latency ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "target": "aliasByNode(Storm.*.*.*.*.*.total-latency-ext.*, 4)"
    }
   ]
  },
  {
   "title": "End-to-end Latency 5 sec",
   "type": "timeseries",
   "description": "End-to-end latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(Storm.*.*.*.*.*.total-latency-ext.*,5), 4)"
    }
   ]
  },
  {
   "title": "End-to-end Latency 30 sec",
   "type": "timeseries",
   "description": "End-to-end latency 30 sec",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(Storm.*.*.*.*.*.total-latency-ext.*,30), 4,5)"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Input Queue Sizes",
   "type": "timeseries",
   "description": "Input queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "target": "substr(Storm.*.*.*.*.*.receive.population.value, 4, 5)"
    }
   ]
  },
  {
   "title": "Output Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "target": "substr(Storm.*.*.*.*.*.sendqueue.population.value, 4, 5)"
    }
   ]
  },
  {
   "title": "Input Queue Sizes AVG 30 sec",
   "type": "timeseries",
   "description": "Input queue average 30 sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "target": "substr(movingAverage(Storm.*.*.*.*.*.receive.population.value, 30), 4, 5)"
    }
   ]
  },
  {
   "title": "Output Queue Sizes AVG 30 sec",
   "type": "timeseries",
   "description": "Output queue average 30 sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "target": "substr(movingAverage(Storm.*.*.*.*.*.sendqueue.population.value, 30), 4, 5)"
    }
   ]
  },
  { "title": "External", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "External Queue Size",
   "type": "timeseries",
   "description": "External queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "target": "Storm.*.*.*.*.*.external-queue-size.*"
    }
   ]
  },
  {
   "title": "External rate",
   "type": "timeseries",
   "description": "External rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "target": "Storm.*.*.*.*.*.external-rate.*"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Storm Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    { "target": "Storm.*.utilization.memory.mb" },
    {
     "target": "alias(movingAverage(Storm.*.utilization.memory.mb, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(Storm.*.utilization.memory.mb, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  {
   "title": "Lachesis Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "target": "lachesis.*.utilization.memory.mb"
    },
    {
     "target": "alias(movingAverage(lachesis.*.utilization.memory.mb, 5), \"moving avg 5 sec\")"
    },
    {
     "target": "alias(movingAverage(lachesis.*.utilization.memory.mb, 30), \"moving avg 30 sec\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storm CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "target": "Storm.*.utilization.cpu.percent"
      },
      {
       "target": "alias(movingAverage(Storm.*.utilization.cpu.percent, 5), \"moving avg 5 sec\")"
      },
      {
       "target": "alias(movingAverage(Storm.*.utilization.cpu.percent, 30), \"moving avg 30 sec\")"
      }
     ]
    },
    {
     "title": "Lachesis CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "targets": [
      {
       "target": "lachesis.*.utilization.cpu.percent"
      },
      {
       "target": "alias(movingAverage(lachesis.*.utilization.cpu.percent, 5), \"moving avg 5 sec\")"
      },
      {
       "target": "alias(movingAverage(lachesis.*.utilization.cpu.percent, 30), \"moving avg 30 sec\")"
      }
     ]
    },
    {
     "title": "Graphite CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "targets": [
      {
       "target": "graphite.*.utilization.cpu.percent"
      },
      {
       "target": "alias(movingAverage(graphite.*.utilization.cpu.percent, 5), \"moving avg 5 sec\")"
      },
      {
       "target": "alias(movingAverage(graphite.*.utilization.cpu.percent, 30), \"moving avg 30 sec\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Reads and Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads",
     "type": "timeseries",
     "description": "Reads",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "target": "Storm.*.*.*.*.*.execute-count.*.value"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "timeseries",
     "description": "Writes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "target": "Storm.*.*.*.*.*.emit-count.*.value"
      }
     ]
    }
   ]
  }
 ]
}